Document: lobby
Title: Debian lobby Manual
Author: <insert document author here>
Abstract: This manual describes what lobby is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/lobby/lobby.sgml.gz

Format: postscript
Files: /usr/share/doc/lobby/lobby.ps.gz

Format: text
Files: /usr/share/doc/lobby/lobby.text.gz

Format: HTML
Index: /usr/share/doc/lobby/html/index.html
Files: /usr/share/doc/lobby/html/*.html
